### ISSUE TITLE
New Bitbucket webhooks, services to be deprecated

### ISSUE THREAD

**Issue by Rarst** [mexitek/myWebHook#3]
Bitbucket announced new "webhooks" system and intends to deprecate current "services" one. This will probably break support for it.

See [The new Bitbucket webhooks](http://blog.bitbucket.org/2015/06/24/the-new-bitbucket-webhooks/).

**Comment by mexitek** [comment]
Booooo!!!!!!!!!! Thanks for the heads-up though. I'll try to get some time to work with the new webhooks. Unless someone wants to contribute. ;)

**Comment by Rarst** [comment]
I might, but no promises right now. :) They say in comments we got about 6 months, so not too urgent.

**Comment by Rarst** [comment]
We are now 2/3rds toward (vague) deprecation time... It's about to get urgent like these things do, will try to get to this some time.

**Comment by rrodrigonuez** [comment]
JFY.

If you want to use Bitbuket WebHooks you will need to change the payload for:
$payload = json_decode( file_get_contents( 'php://input' ), true );

Documented here: https://bitbucket.org/site/master/issues/11537/webhooks-payload-empty

**Comment by mexitek** [comment]
Have you confirmed this works for you? Can you submit a pull request?

**Comment by rrodrigonuez** [comment]
sorry buddy no time for a pull request :(

I built my own script using bitbucket webhooks and I can asure that this will work:
```php
$payload = json_decode( file_get_contents( 'php://input' ), true );
if ( isset( $payload['push'] ) ) {
  $lastChange = $payload['push']['changes'][ count( $payload['push']['changes'] ) - 1 ]['new'];
  $branch     = isset( $lastChange['name'] ) && ! empty( $lastChange['name'] ) ? $lastChange['name'] : '';
}
```

Feel free to use it and test it :D

**Comment by solosik** [comment]
Are there any news guys?

**Comment by rafilkmp3** [comment]
hi , i really need make this work with new bitbucket webhook system , can you make your magic ?
